#!/usr/bin/env bash
# Type-check the app sources for real, without an Android SDK.
#
# There is no SDK in this environment (dl.google.com is blocked), so :app is
# normally only compiled by CI — and twice that has meant pushing a function
# called from two places and defined in none. Robolectric publishes
# `org.robolectric:android-all`, a COMPLETE framework jar, to Maven Central,
# which the build already reaches. Compiled against that plus the real :core
# jar, the Kotlin compiler resolves everything and its errors are all genuine.
#
# This is not a substitute for CI: it has no aapt, so resources and the
# manifest are unchecked, and android-all is a stubbed runtime rather than the
# exact API 34 surface. It catches the class of mistake that was reaching CI.
set -eu
cd "$(dirname "$0")/.."
SD="${TMPDIR:-/tmp}/anvil-appcheck"
mkdir -p "$SD"

AJ="tools/lib/android-all.jar"
if [ ! -f "$AJ" ]; then
  echo "appcheck: fetching the framework jar (once, ~132 MB)..."
  mkdir -p "$SD/fetch" tools/lib
  cat > "$SD/fetch/settings.gradle" <<'G'
rootProject.name = 'androidjar'
G
  cat > "$SD/fetch/build.gradle" <<'G'
repositories { mavenCentral() }
configurations { deps }
dependencies { deps 'org.robolectric:android-all:14-robolectric-10818077' }
tasks.register('fetch', Copy) { from configurations.deps; into "$buildDir/out" }
G
  ./gradlew -p "$SD/fetch" fetch -q || { echo "appcheck: could not fetch"; exit 1; }
  cp "$SD"/fetch/build/out/android-all-*.jar "$AJ"
fi

./gradlew :core:jar -PcoreOnly -q 2>/dev/null
CORE=$(ls core/build/libs/*.jar 2>/dev/null | head -1)
[ -z "$CORE" ] && { echo "appcheck: no core jar"; exit 1; }

find_jar() { find ~/.gradle/caches -name "$1" 2>/dev/null | head -1; }
CP=$(find_jar "kotlin-compiler-embeddable-*.jar")
STD=$(find_jar "kotlin-stdlib-2*.jar")
ANN=$(find_jar "annotations-13.0.jar")
COR=$(find_jar "kotlinx-coroutines-core-jvm-*.jar")
TRV=$(find_jar "trove4j-*.jar")

# androidx is published to Google's Maven, which the egress proxy blocks, so
# the two symbols this app uses from it are stubbed at their real signatures.
# Keep these in step with the real API if the usage ever grows.
mkdir -p "$SD/gen/androidx/core/view"
cat > "$SD/gen/androidx/core/view/ViewCompat.java" <<'J'
package androidx.core.view;
import android.view.View;
public final class ViewCompat {
  public interface OnApplyWindowInsetsListener {
    WindowInsetsCompat onApplyWindowInsets(View v, WindowInsetsCompat insets);
  }
  public static void setOnApplyWindowInsetsListener(View v, OnApplyWindowInsetsListener l) {}
}
J
cat > "$SD/gen/androidx/core/view/WindowInsetsCompat.java" <<'J'
package androidx.core.view;
import androidx.core.graphics.Insets;
public final class WindowInsetsCompat {
  public static final class Type {
    public static int systemBars() { return 0; }
    public static int displayCutout() { return 0; }
  }
  public Insets getInsets(int typeMask) { return null; }
}
J

cat > "$SD/gen/androidx/core/view/WindowCompat.java" <<'J'
package androidx.core.view;
import android.view.Window;
public final class WindowCompat {
  public static void setDecorFitsSystemWindows(Window w, boolean fits) {}
}
J

cat > "$SD/gen/androidx/core/view/WindowInsetsControllerCompat.java" <<'J'
package androidx.core.view;
import android.view.View;
import android.view.Window;
public final class WindowInsetsControllerCompat {
  public static final int BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE = 2;
  public WindowInsetsControllerCompat(Window w, View v) {}
  public void hide(int types) {}
  public void setSystemBarsBehavior(int b) {}
  public int getSystemBarsBehavior() { return 0; }
}
J
mkdir -p "$SD/gen/androidx/core/graphics"
cat > "$SD/gen/androidx/core/graphics/Insets.java" <<'J'
package androidx.core.graphics;
public final class Insets { public int left, top, right, bottom; }
J

# R is generated by aapt at build time; a stub is enough to type-check against
mkdir -p "$SD/gen/art/plume/anvil"
python3 - "$SD/gen/art/plume/anvil/R.java" <<'PY'
import re, sys, glob, os
out = sys.argv[1]
kinds = {'string': set(), 'dimen': set(), 'color': set(), 'drawable': set(), 'style': set()}
for f in glob.glob('app/src/main/res/values*/*.xml'):
    s = open(f).read()
    for m in re.finditer(r'<(string|dimen|color|style|item)\s+name="([^"]+)"(?:\s+type="(\w+)")?', s):
        k = m.group(3) or m.group(1)
        if k in kinds: kinds[k].add(m.group(2))
for f in glob.glob('app/src/main/res/drawable/*.xml'):
    kinds['drawable'].add(os.path.basename(f)[:-4])
with open(out, 'w') as fh:
    fh.write('package art.plume.anvil;\npublic final class R {\n')
    for k, names in kinds.items():
        fh.write('  public static final class %s {\n' % k)
        for n in sorted(names):
            fh.write('    public static final int %s = 0;\n' % n)
        fh.write('  }\n')
    fh.write('}\n')
PY

java -cp "$CP:$STD:$ANN:$COR:$TRV" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
  -d "$SD/out" -no-stdlib -nowarn \
  -cp "$STD:$CORE:$AJ" \
  app/src/main/kotlin/art/plume/anvil/*.kt \
  "$SD/gen/art/plume/anvil/R.java" \
  "$SD/gen/androidx/core/view/ViewCompat.java" \
  "$SD/gen/androidx/core/view/WindowInsetsCompat.java" \
  "$SD/gen/androidx/core/view/WindowCompat.java" \
  "$SD/gen/androidx/core/view/WindowInsetsControllerCompat.java" \
  "$SD/gen/androidx/core/graphics/Insets.java" 2>&1 \
  | grep -E '^app/.*error:' > "$SD/errors.txt" || true

if [ -s "$SD/errors.txt" ]; then
  cat "$SD/errors.txt"
  echo "--- $(wc -l < "$SD/errors.txt") error(s) ---"
  exit 1
fi
echo "appcheck: clean"
